[theme]
base = "light"
primaryColor = "#005EB8"
backgroundColor = "#FAF8F4"
secondaryBackgroundColor = "#F0ECE3"
textColor = "#16232E"
font = "sans serif"

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
